version: '3.9'
services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - redis
    env_file:
      - apps/api/.env.api.example
    environment:
      - NODE_ENV=development

  batch:
    build:
      context: .
      dockerfile: apps/batch/Dockerfile
    depends_on:
      - redis
    env_file:
      - apps/batch/.env.batch.example
    restart: unless-stopped

volumes:
  redis_data:
