-- ============================================================
-- 공항 통합 정보 앱 Oracle DB 스키마
-- Oracle 19c 이상
-- ============================================================

-- 운항 실시간 현황 (FLIGHT_DATE 기준 파티셔닝)
CREATE TABLE FLIGHT_STATUS (
  FLIGHT_ID         VARCHAR2(100) NOT NULL,
  AIRPORT_CODE      VARCHAR2(10)  NOT NULL,
  AIRPORT_TYPE      VARCHAR2(10)  NOT NULL,
  AIRLINE           VARCHAR2(100),
  FLIGHT_NO         VARCHAR2(20)  NOT NULL,
  MASTER_FLIGHT_NO  VARCHAR2(20),
  IS_CODESHARE      NUMBER(1)     DEFAULT 0,
  DIRECTION         VARCHAR2(15)  NOT NULL,
  TERMINAL          VARCHAR2(10),
  GATE              VARCHAR2(10),
  SCHEDULED_TIME    TIMESTAMP     NOT NULL,
  ESTIMATED_TIME    TIMESTAMP,
  ACTUAL_TIME       TIMESTAMP,
  STATUS            VARCHAR2(20)  NOT NULL,
  ORIGIN            VARCHAR2(10),
  DESTINATION       VARCHAR2(10),
  BAGGAGE_CLAIM     VARCHAR2(10),
  EXIT_GATE         VARCHAR2(10),
  VIA               VARCHAR2(10),
  FLIGHT_TYPE       VARCHAR2(15),
  FLIGHT_DATE       DATE          NOT NULL,
  CREATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_FLIGHT_STATUS PRIMARY KEY (FLIGHT_ID, FLIGHT_DATE)
) PARTITION BY RANGE (FLIGHT_DATE) INTERVAL (NUMTODSINTERVAL(1, 'DAY')) (
  PARTITION P_INIT VALUES LESS THAN (DATE '2025-01-01')
);

-- 시즌 정기 스케줄
CREATE TABLE FLIGHT_SCHEDULE (
  SCHEDULE_ID       VARCHAR2(100) NOT NULL PRIMARY KEY,
  AIRPORT_CODE      VARCHAR2(10)  NOT NULL,
  AIRLINE           VARCHAR2(100),
  FLIGHT_NO         VARCHAR2(20)  NOT NULL,
  DIRECTION         VARCHAR2(15)  NOT NULL,
  OPERATING_DAYS    VARCHAR2(7),
  SEASON_CODE       VARCHAR2(10),
  SEASON_START      DATE,
  SEASON_END        DATE,
  ORIGIN            VARCHAR2(10),
  DESTINATION       VARCHAR2(10),
  SCHEDULED_TIME    VARCHAR2(5),
  UPDATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP
);

-- 주차 현황
CREATE TABLE PARKING_STATUS (
  PARKING_ID        VARCHAR2(100) NOT NULL PRIMARY KEY,
  AIRPORT_CODE      VARCHAR2(10)  NOT NULL,
  AIRPORT_TYPE      VARCHAR2(10)  NOT NULL,
  ZONE              VARCHAR2(50)  NOT NULL,
  TERMINAL          VARCHAR2(10),
  PARKING_TYPE      VARCHAR2(10),
  TOTAL_SPOTS       NUMBER(6)     NOT NULL,
  OCCUPIED_SPOTS    NUMBER(6)     NOT NULL,
  AVAILABLE_SPOTS   NUMBER(6)     NOT NULL,
  CONGESTION_LEVEL  VARCHAR2(15)  NOT NULL,
  RECORDED_AT       TIMESTAMP     NOT NULL,
  UPDATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP
);

-- 입출국장 혼잡도
CREATE TABLE IMMIGRATION_STATUS (
  IMMIGRATION_ID    VARCHAR2(100) NOT NULL PRIMARY KEY,
  AIRPORT_CODE      VARCHAR2(10)  NOT NULL,
  TERMINAL          VARCHAR2(10)  NOT NULL,
  DIRECTION         VARCHAR2(15)  NOT NULL,
  GATE              VARCHAR2(10)  NOT NULL,
  WAITING_COUNT     NUMBER(6)     DEFAULT 0,
  WAITING_KOR       NUMBER(6)     DEFAULT 0,
  WAITING_FOR       NUMBER(6)     DEFAULT 0,
  CONGESTION_LEVEL  VARCHAR2(15)  NOT NULL,
  RECORDED_AT       TIMESTAMP     NOT NULL,
  UPDATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP
);

-- 날씨 정보
CREATE TABLE WEATHER_INFO (
  WEATHER_ID        VARCHAR2(100) NOT NULL PRIMARY KEY,
  AIRPORT_CODE      VARCHAR2(10)  NOT NULL,
  CITY_NAME         VARCHAR2(100),
  TEMPERATURE       NUMBER(5,2),
  FEELS_LIKE        NUMBER(5,2),
  HUMIDITY          NUMBER(3),
  WIND_SPEED        NUMBER(5,2),
  WEATHER_CODE      VARCHAR2(50),
  WEATHER_ICON_URL  VARCHAR2(200),
  FORECAST_DATE     TIMESTAMP,
  UPDATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP
);

-- 관리자 계정
CREATE TABLE ADMIN_USER (
  ADMIN_ID          VARCHAR2(100) NOT NULL PRIMARY KEY,
  EMAIL             VARCHAR2(200) NOT NULL,
  PASSWORD_HASH     VARCHAR2(255) NOT NULL,
  NAME              VARCHAR2(100),
  ROLE              VARCHAR2(20)  DEFAULT 'ADMIN',
  IS_ACTIVE         NUMBER(1)     DEFAULT 1,
  LAST_LOGIN_AT     TIMESTAMP,
  CREATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT UQ_ADMIN_EMAIL UNIQUE (EMAIL)
);

-- 디바이스 (익명 사용자)
CREATE TABLE DEVICE (
  DEVICE_ID         VARCHAR2(100) NOT NULL PRIMARY KEY,
  PUSH_TOKEN        VARCHAR2(500),
  PLATFORM          VARCHAR2(10)  NOT NULL,
  APP_VERSION       VARCHAR2(20),
  NOTIFICATION_ON   NUMBER(1)     DEFAULT 1,
  CREATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP,
  UPDATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP
);

-- 즐겨찾기 항공편
CREATE TABLE FAVORITE_FLIGHT (
  FAVORITE_ID       NUMBER        GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DEVICE_ID         VARCHAR2(100) NOT NULL,
  FLIGHT_NO         VARCHAR2(20)  NOT NULL,
  AIRPORT_CODE      VARCHAR2(10)  NOT NULL,
  DIRECTION         VARCHAR2(15)  NOT NULL,
  NOTIFY_DELAY      NUMBER(1)     DEFAULT 1,
  NOTIFY_CANCEL     NUMBER(1)     DEFAULT 1,
  NOTIFY_BOARD      NUMBER(1)     DEFAULT 1,
  CREATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT FK_FAV_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE(DEVICE_ID) ON DELETE CASCADE,
  CONSTRAINT UQ_FAV UNIQUE (DEVICE_ID, FLIGHT_NO, AIRPORT_CODE)
);

-- 푸시 알림 발송 이력
CREATE TABLE NOTIFICATION_LOG (
  LOG_ID            NUMBER        GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  DEVICE_ID         VARCHAR2(100) NOT NULL,
  FLIGHT_NO         VARCHAR2(20)  NOT NULL,
  NOTIFY_TYPE       VARCHAR2(20)  NOT NULL,
  TITLE             VARCHAR2(200),
  BODY              VARCHAR2(500),
  IS_SENT           NUMBER(1)     DEFAULT 0,
  SENT_AT           TIMESTAMP,
  ERROR_MSG         VARCHAR2(1000),
  CREATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP
);

-- 배치 실행 로그
CREATE TABLE BATCH_LOG (
  LOG_ID            NUMBER        GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  JOB_NAME          VARCHAR2(100) NOT NULL,
  AIRPORT_CODE      VARCHAR2(10),
  STATUS            VARCHAR2(10)  NOT NULL,
  RECORDS_COUNT     NUMBER(10)    DEFAULT 0,
  ERROR_MESSAGE     VARCHAR2(4000),
  STARTED_AT        TIMESTAMP     NOT NULL,
  FINISHED_AT       TIMESTAMP,
  DURATION_MS       NUMBER(10)
);

-- ============================================================
-- 인덱스
-- ============================================================
CREATE INDEX IDX_FLIGHT_DATE_AIRPORT   ON FLIGHT_STATUS(FLIGHT_DATE, AIRPORT_CODE, DIRECTION)      LOCAL;
CREATE INDEX IDX_FLIGHT_NO_DATE        ON FLIGHT_STATUS(FLIGHT_NO, FLIGHT_DATE)                    LOCAL;
CREATE INDEX IDX_PARKING_AIRPORT       ON PARKING_STATUS(AIRPORT_CODE, UPDATED_AT DESC);
CREATE INDEX IDX_IMMIGRATION_AIRPORT   ON IMMIGRATION_STATUS(AIRPORT_CODE, TERMINAL, DIRECTION);
CREATE INDEX IDX_WEATHER_AIRPORT       ON WEATHER_INFO(AIRPORT_CODE, FORECAST_DATE DESC);
CREATE INDEX IDX_FAV_DEVICE            ON FAVORITE_FLIGHT(DEVICE_ID);
CREATE INDEX IDX_FAV_FLIGHT_NO         ON FAVORITE_FLIGHT(FLIGHT_NO, AIRPORT_CODE);
CREATE INDEX IDX_NOTIF_DEVICE_DATE     ON NOTIFICATION_LOG(DEVICE_ID, CREATED_AT DESC);
CREATE INDEX IDX_BATCH_LOG_JOB_DATE    ON BATCH_LOG(JOB_NAME, TRUNC(STARTED_AT));
